### ISSUE TITLE
CI support

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#146]
we can add Travis CI (free to open source projects) so we'll have default test runs + pr checks

**Comment by eshaham** [comment]
@lielran we should probably add tests first... 😄 
running a CI just for linting isn't that beneficial IMO.
I've been wanting to add integration tests for a while now, but it's not that easy since we need to fetch and anonymize the data for each scraper. thoughts?

**Comment by esakal** [comment]
I will let @eshaham to decide about this one. As using a CI is most effective as part of deployment process and he is the one that deploy this library.

Obviously if we had unit tests and would be relevant also to pull requests but as we are dealing with sensitive data and rely on data sources that are not in our control I'm not sure it would be easy to add unit tests.

Regarding the lint this, as @eshaham added [pre-commit](https://github.com/eshaham/israeli-bank-scrapers/blob/master/package.json#L18) enforcement we are covered in that area

@eshaham  @lielran  wdyt?

**Comment by eshaham** [comment]
Let's add it only after we have a first test.
Closing this for now.

**Comment by baruchiro** [comment]
> Let's add it only after we have a first test.

@eshaham Now is the time?

**Comment by baruchiro** [comment]
Here are the stages of the proposal I am thinking about:
I present them as steps, since it's pretty obvious that it's all too much to implement at once. So each stage has value in itself (in my opinion).

1. **Code Owners:** Github allows us to enforce [Code Owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) by file, when Pull Request opens, if the file is modified, Code Owner will be set as a reviewer.
2. **Local Auto Test**: Instead of the Code Owner for each PR having to prepare an environment for the test (Clone, Checkout to PR merge, create test template file, run the test), there will be an automated script that will accept the PR number and a constant settings file, and run the test.
3. **Github API / Status Checks**: Send an automatic message (user-approved \ CI message (called "Status Check") when the local test passes.
4. **Dockerizing**.
