### ISSUE TITLE
tnx identifier should be String

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#147]
in order to not limit our self -we need to change the ID of tnx to String

**Comment by esakal** [comment]
Hi, the same answer as I wrote in #148 . Does it improve functionality or fix a bug? 

The property name `identifier` is a bit confusing because `identifier` usually refer to unique id. Here it refer to Asmachta (אסמכתא). All the companies that this library scrape provide Asmachta as numbers and this is why I assume @eshaham defined this property as number. Are you familiar with a scraper that return Asmachta as a string?

**Comment by lielran** [comment]
same here. not urgent but better to save it as a string for not dealing with the issue in a future vendor.

**Comment by eshaham** [comment]
@lielran the idea was indeed to return Asmachta for scrapers which support it.
Discount scraper is an example.
I wouldn't go with Asmachta for a field name, but I agree that identifier may be confusing.
Got any better names?

**Comment by eshaham** [comment]
@esakal ok.
I don't really see the need in changing the type of the field to a String, until something prompts us to do so. Closing this issue for now.
