### ISSUE TITLE
Separate scrappers for it's own lib

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#151]
what do you think of separate the scrapper in its own lib/repo? 
I case of bugs(in scrapper) we'll have the option to rollback only the scrapper older version without changing the lib and other scrapper code. 

what do you think about it?

**Comment by esakal** [comment]
I don't see how we benefit from it as it will complicate the devop process. We could use mono repo approach but again I'm not sure how valuable it will be as most of the times the bugs are created due to changes in the vendors site and not due to a developer that write buggy code. 

Maybe I'm missing something, @eshaham wdyt?

**Comment by eshaham** [comment]
After reading this again, I just got what @lielran's meant.
Yet, I think it a lot of overhead to maintain separate repos for different scrapers, and believe that most of the time 95% of the scrapers functionality works.
Closing this for now.
