### ISSUE TITLE
transaction information 

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#153]
I found out that Isracard provides more information that currently exposes in the transaction object:
```
{
      type: string, // can be either 'normal' or 'installments'
      identifier: int, // only if exists
      date: string, // ISO date string
      processedDate: string, // ISO date string
      originalAmount: double,
      originalCurrency: string,
      chargedAmount: double,
      description: string,
      memo: string, // can be null or empty
      installments: {
        number: int, // the current installment number
        total: int, // the total number of installments
      },
      status: string //can either be 'completed' or 'pending'
    }
```

<img width="649" alt="screen shot 2018-07-26 at 11 48 45 am" src="https://user-images.githubusercontent.com/1004667/43251992-26ce37a2-90ca-11e8-9fea-9512acc8182e.png">

I know that other vendors(mostly banks) don't hold this kind of infomation but it looks like super intersting infomation and we can use it to accurate the date objects(from just date to date + time).

**Comment by esakal** [comment]
Hi, I think that @eshaham tried to find the most common properties that must (of not all) vendors support. It is quite reasonable since not providing a data that is missing during scraping will affect the scraping credibility (as the user will not be able to distinguish between valid empty fields and fields that are empty just because we don't have information about them).

**Comment by lielran** [comment]
if you aim just for the common you are also missing the added value that some vendors can provide you. since it is on the level of the vendor then we can do optional data. the user can expect it will return in case of `Isracard` for example while in the case of `Hapoalim` it will be empty.

**Comment by lielran** [comment]
why is the transaction is common in the first place? since the input/vendor is not the same why should the output be the same? the user knows he is targeting specific vendor data. 

the other option is to add a custom section(json object) where we can add extra data if we can.

**Comment by eshaham** [comment]
@lielran interesting point.
I've had this in my mind for some time. What @esakal said is correct - I've been trying to keep a common API across the scrapers.
Having said that, I do see value in returning extra data for a specific scraper, but this will only work if  
A. It is returned under an extra section as you suggested and
B. Properly documented

@esakal wdyt?

**Comment by lielran** [comment]
I've noticed also the "common part" have few issues:
1) description is sometimes cut in the middle of the String. wherein the details you can see the whole String. 
2) the transaction dates do not contain the time - only the actual dates 

in both cases, it can be useful for "common" parts

**Comment by esakal** [comment]
> description is sometimes cut in the middle of the String. wherein the details you can see the whole String.
the transaction dates do not contain the time - only the actual dates

I think this is a bug in the scrapers as they should try to scrape the most relevant value if exists. @lielran I think you should improve those scrapers as mentioned.

Reviewing the snapshot in the original thread. @lielran which information would you like to add? because the information about the business can be considered as common information (as all credit cards companies will/should provide them). Are you looking also for the second section? הנחה, מבצע, מעמ....?

**Comment by eshaham** [comment]
@lielran I'm all for adding the time to the transactions, as long as most scrapers support them.
As for the cutting of the descriptions, I believe that it is the beehavior in most banks / credit cards.

Would solving theses be an additional http call?
Because if so, it will slow down scraping drastically.
Again, that's also acceptable, but perhaps we should add another parameter allowing users to decide whether they need that extra data.

**Comment by lielran** [comment]
@esakal  - I actually not sure what all of them means :) 

@eshaham  the info that I find important is: 
- business details : **full name** location, address, phone,...
- buying time in minutes (local date time) **- require anohter call for each line**
another information that we easly collect:
- credit card paying date( every 1,10,15 each month)  - not an extra call
- the type of the card (Mastercard,Visa,...)  - not an extra call
- overall usage (  ניצול מסגרת אשראי ) - not an extra call
- holder name - not an extra call
- bank details that the credit card associal with  - not an extra call

I didn't check all the vendors.

I sounds like we are aggre on the need. lets discuss how we should do it:
1) seperate scraper (for the extra https calls) 
2) none extra calls can be added to the regular scappers 
3) should we store the "new" data in diffrent section? which be null if case other vendor don't have this information?

**Comment by eshaham** [comment]
@lielran all these fields sound interesting.
I'm all for adding them, as I said, as long as most scrapers can support them on without additional http requests.
As for information requiring more http requests, I don't think we should go down the path of creating new scrapers, but rather add an option to get extra info.
