### ISSUE TITLE
Leumi Card - unknown transaction type

### ISSUE THREAD

**Issue by shmaram** [eshaham/israeli-bank-scrapers#163]
Hi

I think you are missing a transaction type for Leumi Card. 
I get the following error :
{"success":false,"errorType":"generic","errorMessage":"unknown transaction type עסקת 30 פלוס\t"}

**Comment by esakal** [comment]
@eshaham It seems that we map all transaction types (7 types) as `NORMAL_TXN_TYPE` and only 1 type as `INSTALLMENTS_TXN_TYPE`. As we are not using those type to anything else, Instead of keep managing them maybe we should consider defaulting to `NORMAL_TXN_TYPE` instead of throwing the mentioned error, what do you think?

If you agree then let me know if we need to keep the list of types or just keep the installment type.

**Comment by eshaham** [comment]
@esakal I feel like we may be losing an important type of info which may be useful later on.
Let's keep mapping new transaction types, for now, I believe we will see less of those at some point.
