### ISSUE TITLE
Dependency update stratgy

### ISSUE THREAD

**Issue by Urigo** [eshaham/israeli-bank-scrapers#181]
What do you think is your dependency update strategy?

Probably now you are probably updating just when you need an update for some reason.

What do you think about using a tool like RenovateBot, to keep dependencies up to date?
As most of the code here is being used daily I believe that even without tests we can have good confidence of finding bugs relatively fast.

If we keep dependencies untouched for a long while, there is more chance upgrading would become a pain.

Wonder about your thoughts

**Comment by eshaham** [comment]
@Urigo great idea.
The only problem I see with this is that we don't have unit/integration tests, and so have a tool automatically create pull requests would not remove the overhead of actually making sure everything is still working. wdyt?

**Comment by Urigo** [comment]
@eshaham yes there is not a lot of guarantees here except the fact that most of the people using/developing this are using it daily (at least me...) so if we merge a bad update, we would learn about the issue relatively quickly.
In my personal opinion it is worth it...

**Comment by Urigo** [comment]
also, personally, I would increase the minimum version of Node required and remove some babel transformations...

**Comment by eshaham** [comment]
> @eshaham yes there is not a lot of guarantees here except the fact that most of the people using/developing this are using it daily (at least me...) so if we merge a bad update, we would learn about the issue relatively quickly.
In my personal opinion it is worth it...

ok, I'm convinced. @esakal, think differently?

**Comment by esakal** [comment]
I favor the idea of updating dependencies automatically. 

The question is how far will let the process go, will it also deploy to npm automatically? if not then most developers will not get new versions as they probably consume this library from NPM. Even if the process will release to NPM, `package-lock.json` will not let developers get new versions until they will explicitly ask to update it.  

So I'm not sure if can actually add such a process without some automatic unit-tests. But I think that travis-ci support code that runs puppeteer as many people use it for e2e testing, so it might not be that hard to plug it all together.

I might be wrong here, curious to hear what you think.

Since people usually consume this library as-is and doesn't develop inside this repo, they will get new versions only after re-fetching `node-modules` folder that frequently. If you agree then we do need unit-tests. But it shouldn't be hard to add unit-tests as we rely on 

> also, personally, I would increase the minimum version of Node required and remove some babel transformations...

@Urigo Do you experience a compatibility issues or it just annoy you that it is stuck on a version from mid 2017?

**Comment by Urigo** [comment]
adding unit tests is always great.

about releasing to npm, I think it's good we won't release a new version for users on each update and only when we feel there is a need.
But, I don't think it means we shouldn't update automatically because maintainers like us can use it daily from source or we can create an automatic `alpha` releases with a hash (we do that for all of our open source libraries for each commit).

About the compatibility thing, the main reason is that I would prefer to use native code instead of transpilation.
It is faster, the build step is faster or none existent and the amount of people still using Node older then 10 is very minimal, adoption is very good with that.

**Comment by eshaham** [comment]
@esakal @Urigo so I think we all agree we should integrate something to create PRs with updated dependencies automatically.

regarding upgrading to use node 10, let's wait with that. I've been doing scraping with Google cloud functions (Google's take on AWS lambda), which supports Puppeteer out of the box. It only runs node 8, and even that is still in beta. Don't see a good reason to rush things, even at the cost of the need to transpile the code first.

**Comment by esakal** [comment]
I'm closing this issue as this library is using dependabot do update dependencies automatically
