### ISSUE TITLE
feature/configure-chrome-executable-path

### ISSUE THREAD

**Issue by kokoapps** [eshaham/israeli-bank-scrapers#240]
I want to submit a PR for allowing the configuration of chrome executable path in puppeteer.
Do I need a special permission for sending the PR?

**Comment by esakal** [comment]
Hi @kokoapps, you don't need special permission to create a PR. You should just fork this repository and then create a PR from your repository to this one. It is quite simple.

that being said, there is already an exists PR that does exactly what you want. see #235. Actually it allow you do use this library with `puppeteer-core` which might be useful for you (since I don't see any reason passing the path without using `puppeteer-core`. Please review  #235 and let me know if this is what you are looking for or if you aim to something different.
