### ISSUE TITLE
Leumi Card is getting new transaction with amout of 0

### ISSUE THREAD

**Issue by DvirNaim** [eshaham/israeli-bank-scrapers#249]
when the scraper is getting a new transaction, it displays it as 0. 

i.e - 
לאומי קארד: זיכוי - צומת ספרים עזריאלי על סך 0₪ בתאריך 2019-8-19 בסטטוס pending בחשבון 3715

although the transaction is over 0 (as we can see in LeumiCard's app)

**Comment by esakal** [comment]
Hi @DvirNaim , this happens since in Leumi card when the transaction is in status pending, the api return amount 0. 

from your example I can see that the status is `pending` thus the amount is 0.  This is poor result but inevitable one.

I suggest you to filter pending transactions out as they are not guaranteed for any scraper.

**Comment by liranso** [comment]
Hi @esakal 
i cannot find a "pending" status on transactions with "actualPaymentAmount" = 0
however i did find a pattern where these pending transactions have both "actualPaymentAmount" and "paymentDate" equals to **null**
we can filter these transaction out.

Also, i noticed that sometimes the last api call to leumi card returns a json with result=null - which causes the scraper to fail. we can also add the following code to avoid that 
`if (!data.result) {
    return transactionsByAccount;
  }`

in "fetchTransactionsForMonth" method

WDYT?

**Comment by esakal** [comment]
Hi @liranso, we don't actually have a bug here hence this issue should have been closed. So I'm referring to your comment separately. 

> i cannot find a "pending" status on transactions with "actualPaymentAmount" = 0
however i did find a pattern where these pending transactions have both "actualPaymentAmount" and "paymentDate" equals to null

Once a transaction is marked as `Pending` all the other fields are not guaranteed to include valid values. This is true for all scrapers. The reason is that each institute handle `pending` transactions differently and provide partial data or temporary data. 

We shouldn't filter those out as they are part of the data provided by the institute. Each application should decide on its own if it should treat those pending ones or filter them out as you suggested. In my applications for example I'm ignoring both pending and future transactions which guarantee that I treat only final transactions that would not be modified in future scraping.

> Also, i noticed that sometimes the last api call to leumi card returns a json with result=null - which causes the scraper to fail. we can also add the following code to avoid that
if (!data.result) { return transactionsByAccount; }

This one was handled 21 days ago as part of #234 but still pending new release. @liranso we are thinking about an automatic deployment process that will shorten the time between fixing bugs and merging them to master, we already layout testing framework and I assume we will be able to complete the automatic process sometime soon. @eshaham in the meanwhile can you release a new version?

**Comment by liranso** [comment]
@esakal i missed the think with how we treat pending transaction in the code, now i see what you mean. 
thanks

**Comment by esakal** [comment]
@liranso 👍 feel free to open new issues if you have further questions.
