### ISSUE TITLE
Question. New scraper guidelines

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#363]
Any guidelines about how to create a new scraper?
Use the chrome inspector looking for the page structure?

**Comment by esakal** [comment]
Hello @gczobel, which institute are you planning to scrape?

1. You should read the [contributing.md](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md) file, it contains useful information.
2. You then need to decide if you are going to scrape the web application or the mobile api. It actually depends on which api you have access to in your environment.
3. use the chrome inspector to learn if that institute has a structured api (rest or anything else that you can access directly using `curl` or [postman](https://www.postman.com/) or something similar - if so you can inherit from `BaseScraper` and fetch the data directly without simulating a browser.
4. otherwise you should inherit from `BaseScraperWithBrowser` 

I hope it helps.
Eran
