### ISSUE TITLE
Isracard shotef +60

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#397]
Hi,
I'm having an issue with Business Isracard CC.
These card gives +60 days from the day the charge is created. For example, charges from 01/March are part of the May statement.

Now, in `getAllMonthMoments` in `dates.js`
https://github.com/eshaham/israeli-bank-scrapers/blob/ad5dda57bddbdcfc53aa7db3f92dfec475f3e647/src/scrapers/base-isracard-amex.js#L160

```
async function fetchAllTransactions(page, options, startMoment) {
  const allMonths = (0, _dates.default)(startMoment, true);
```

The `allMonths` are calculated from the startMoment up to the current month + 1. So there is no way to capture the May statement (where the March transactions are saved).

Any idea how to solve this?

**Comment by esakal** [comment]
hi
are those transactions visible in their site? can you provide a snapshot and blur your sensitive information? 

If it does appear there and it is only a start time it should be possible to allow custom end time

**Comment by gczobel** [comment]
Yes, is visible in the site. You only need to change the date to May.
See the screenshots.

![dateselection](https://user-images.githubusercontent.com/754466/77819964-e930b700-70ef-11ea-90f0-505bc1d0b1fd.png)
![CC_Shotef60](https://user-images.githubusercontent.com/754466/77819965-ec2ba780-70ef-11ea-8380-7064d4d930db.png)

**Comment by gczobel** [comment]
@esakal No workaround for this?

**Comment by esakal** [comment]
Hi,
I can mark this request as an enhancement and we can add it to the queue. It might take a while thou because we have some infrastructure improvements we are planning and has higher priority.

In the meanwhile you can easily fork this library and modify the code, it is quite easy as you don't really need to consider breaking api changes and other things that we need to think about before adding it to the official version:

1. Fork this repository
2. in [dates.js line 9](https://github.com/eshaham/israeli-bank-scrapers/blob/ae252e2991fddb174044f9dab00af482b5871904/src/helpers/dates.ts#L9) change number `1` to `2`.
3. consider testing the library as mentioned here
4. `npm run build` the library. 
5. `npm pack` to create a `tgz` file of your own version.
6 copy the tgz file into your project into `libs/file-name.tgz`
7. run `npm i file:libs/file-name.tgz` (obviously replace `file-name` here with the actual file name)

Let me know if it helped.
Eran

**Comment by gczobel** [comment]
The workaround is ok...
But please, mark the issue as a enhancement.

Thanks!
