### ISSUE TITLE
Returning raw transaction data

### ISSUE THREAD

**Issue by sagiba** [eshaham/israeli-bank-scrapers#418]
Currently the scrapers are only returning the transaction data in the common structure after conversion. Some users might be interested in accessing raw transaction data without any conversion, but this is currently impossible.

Can we add a way to return the raw transaction data in addition to the common format?
I gave it a try for the CAL scrapers here:
https://github.com/sagiba/israeli-bank-scrapers/commit/1a52500aa3f5551314848a8a4a6fc7bb2573942c

i.e. adding a "raw" property to the common transaction structure. Does this seem like a reasonable way? Are there any downsides to always returning this property, or should this be configurable?

Possible alternative is to add an option to return just the raw data as-is without any conversion, and/or to export the convertTransactions method and make it callable externally or overridable. WDYT?

**Comment by esakal** [comment]
@sagiba,  we have two types of scrapers, those who are using the puppeteer doesn't have a real raw transaction because they scrape the minimum information needed to create the structured transaction. Providing the raw transaction is useful only for companies that are scraping the api and not using puppeteer like visa cal. Even for those companies there might be a "detailed" view (extra information on the transaction) that is not always part of the fetched transaction and require additional api calls, providing raw transaction for those companies might also be partial.

The current API of the scrapers as you mentioned is trying to be consist across all companies we support. Since it is relevant only for some of our companies based on the technical decision/ability how we scrape them (api or puppeteer) I'm not sure how we can expose it in the official API.

We are thinking about a way to make our scrapers more extendible which will allow having discrepancy between companies and easily apply to your use-case. If it is not urgent we can wait for the new infrastructure which should be in active development sometime soon.

let's wait to hear from @eshaham.

In the meanwhile as a workaround, you can see my suggestion in [this comment](https://github.com/eshaham/israeli-bank-scrapers/issues/397#issuecomment-612142649)

**Comment by sagiba** [comment]
@esakal, just because a scraper is doing screen scraping using puppeteer vs. using a proper API does not mean that there's no raw data. Look at the Hapoalim scraper for example, it is using puppeteer yet is still receiving JSON. Even if you were doing HTML parsing instead of getting a JSON, there's still raw data and it's still structured, e.g. if you are scraping an HTML table with transactions as its rows, you could create a raw object from that with the column labels as the keys.

Similarly regarding having to make another round-trip to fetch the detailed view, that might be a useful capability, but it can be optional, you can return the partial raw data from the transaction listing that is already scraped today, and an extended format if deep scraping is enabled.

I understand that every company has a different set of properties, and that the official API needs to return the lowest common denominator so that applications using this library can be oblivious to the internals. Yet I don't think there's anything wrong with allowing developers to receive the company-specific formats when they need it. I've been using the project for a year and have maintained my own fork because I wasn't happy with the way CAL transaction processing was done and was too lazy to contribute a proper fix, if I could receive the raw data I could just patch things on the application side without forking the library.

>  If it is not urgent we can wait for the new infrastructure which should be in active development sometime soon.

Can you tell more about this new infrastructure? I'm working on some extensions of my own, would be useful if we could sync.

**Comment by sagiba** [comment]
FYI, I'm experimenting with more flexible ways to have pluggable conversion logic, here:
https://github.com/sagiba/israeli-bank-scrapers/tree/visa-cal-improvements-ts

I'm doing this on the typescript branch because the type checking helps a lot when dealing with the raw transaction types, and also trying to add some test coverage for this delicate area.

Feedback is welcome..

**Comment by esakal** [comment]
Hi,
Can you point on the main differences of the changes you did in your branch?

Keep in mind that i'm still working on the Typescript branch to enable `strict` `noImplicitAny` and `strictNullChecks` flags in `tsconfig.json` so you will probably have conflicts.

**Comment by sagiba** [comment]
What I'm doing is to extract all of the conversion logic from raw transaction data to the common CreditCardTransaction type, into a new [TransactionConverter](https://github.com/sagiba/israeli-bank-scrapers/blob/233ca7ec2776ed0c21ba53ad3f8755c51f2b8073/src/scrapers/visa-cal/converter.ts) class. The idea is that you'd be able to inject an alternative converter to alter the conversion logic, either modifying the way existing properties in the common type are formatted, or adding new ones.

I'm only working on the visa-cal scrapers at the moment, and still experimenting with interface, but once stable it would probably be extendible to other scrapers as well.

Along the way I'm adding safety checks for the [raw transaction types](https://github.com/sagiba/israeli-bank-scrapers/blob/233ca7ec2776ed0c21ba53ad3f8755c51f2b8073/src/scrapers/visa-cal/types.ts), and [unit tests](https://github.com/sagiba/israeli-bank-scrapers/blob/233ca7ec2776ed0c21ba53ad3f8755c51f2b8073/src/scrapers/visa-cal/converter.test.ts) covering the conversion logic.

**Comment by esakal** [comment]
I assume the motivation is to allow people to project the data differently to their applications by replacing the default converter with their custom one? If so I'm not sure it applies to the majority as it is not a practice most people will do. Replacing the converter with your own copy means that once a company changes its' internal and we updates the default converter, users will not be aware of it if they are using the custom converter and after they update the library they will probably detect it at runtime. Also they will not have a good way to "know" what was changed and they will need to manually compare the converters. They can obviously inherit the default one instead but I think there are better ways to do it. 

I might have misunderstood you so feel free to reply with more details if this is the case. otherwise, there are two other ways that I can think of and doesn't compromise the API of the library:
1. provide a boolean property in the options that when enabled expose the raw as a property (what you suggested)
2. provide an optional method in the options that will be a callback like `customizeTransaction(rawTransaction: any, parsedTransaction: Transaction): Transaction`

I don't have a strict opinion whether it should be implemented or not. I would like to get the feedback of @eshaham about your feature request and the options I mentioned above.

**Comment by esakal** [comment]
@eshaham  wdyt?

**Comment by sagiba** [comment]
@esakal 
> I might have misunderstood you so feel free to reply with more details if that is the case.

The application I'm writing keeps the raw data alongside the converted data. So if I ever find a bug in the conversion logic, I can change the converter and re-process any old transactions, even after they disappear from the original bank/card website.

This is a very powerful capability, and already proved handful several times as I found many shortcomings in the default conversion logic (bad or missing identifiers, wrong currency codes, missing scraper-specific fields and more).

When I find such bug I can re-process all of my historical transactions in seconds, without re-scraping them. Having access to the historical raw data means I can also analyze it and come up with the proper conversion logic. This is much easier than trying to work with data that only exists at runtime and evaporates after the conversion is done.

For example, yesterday I noticed that the hapoalim identifiers are not unique. I speculated that another field might be. To test whether this is true, I had to run a query against all of my historical transactions. Because I keep both the raw transactions and the converted ones in a sqlite database, this is really trivial. The identifier for hapoalim in the current conversion code is referenceNumber. Let's check whether it is unique or not:
```sql
select json_extract(raw, '$.referenceNumber'), count(1) cnt, count(distinct date)
from transactions where account_id=5
group by 1 
order by cnt desc limit 3;
```

We can see that we have plenty of duplicates:
```
630|33|29
8547994|16|16
4896015|14|14
```

Now let's check whether another field, "expandedEventDate" is unique:
```sql
select json_extract(raw, '$.expandedEventDate'), count(1) cnt, count(distinct date)
from transactions where account_id=5
group by 1 
order by cnt desc limit 3;
```

```
2019030300001|1|1
2019030300002|1|1
2019030400001|1|1
```

Hooray! no duplicates. We found the right identifier field for this scraper. So now I can just fix the Converter class, and re-run a script to re-convert all of my transactions, locally, without re-scraping anything.

I hope this gives you a better idea of why storing the raw transaction details is a good practice, and why de-coupling the conversion code in a way that allows re-using it to process transactions without re-scraping is powerful.

**Comment by esakal** [comment]
@sagiba thanks for your detailed example, I now better understand how you find it useful. 

What do you think about the following suggestion. Instead of having a new property (that might always be on the Transaction object or conditionally added by option), we can extend the `options` with a method that let users to influence on the resulted transactions. Something like:

```
parseTransaction?: <TResult extends Transaction>(rawTransaction: any, resultTransaction: Transaction) => TResult;
```

In your case the usage of this method is quite trivial, it will be something like:

```
const options = {
   parseTransaction: (transaction: Transaction, rawTransaction: any) =>
   {
      return { 
         ...transaction,
         raw: rawTransaction 
      };
   } 
}
```

@sagiba @eshaham  What do you guys think about this suggestion?

**Comment by sagiba** [comment]
@esakal, the problem with the approach you suggest is that it doesn't allow to re-process existing transactions with the built-in converter. I recommend de-coupling the conversion code from the scraping code, and making the converter a separate standalone component, so that it can be used to process previously stored transactions. This is useful if I'm making a custom modification to a converter, or if a new official version of the library is released with an updated converter. It also makes unit testing the conversion code much easier.

So I'd move all the conversion logic into a Converter class, and allow injecting an alternative options.converter. I'd then export all the built-in converters along with type definitions for the raw transactions. This is essentially what I started doing for the CAL scraper in this this branch: https://github.com/sagiba/israeli-bank-scrapers/tree/visa-cal-improvements-ts/src/scrapers/visa-cal

This will make the code far more extendible, without sacrificing backward-compatibility or easy-of-use for those who don't care about these capabilities.

**Comment by esakal** [comment]
I think there are two suggestions here that you would like to promote together but they are still separate:
1. a way to expose the raw data on the transaction object so it will be accessible to the application using the library
2. a refactoring of the scraper to separate the conversion logic from the scrapers. 

The first one is easier to promote and I think you should consider them separately.

**Comment by sagiba** [comment]
`#2` is far more important. In fact, if we only do `#2`, and the converter is injectable, then `#1` can be achieved by injecting a converter that preserves the raw data, similar to what you suggested before with `parseTransaction`.

I don't understand the dilemma here. Separating the conversion logic makes the code cleaner, easier to test, and easier to re-use. And we can keep full backward-compatibility in the process. What are you concerned about?

**Comment by eshaham** [comment]
@sagiba @esakal I agree with both of you... 😄 

Yes, it makes sense to extract conversion logic, and even to allow to override it, although, as Eran said, it could lead to unwanted experiences if the site changes. We could do that with a disclaimer that we do not recommend this approach for most users.

At the same time, I still don't understand what is wrong with @esakal's suggestion about attaching the raw data to the result. In such case, we manage to stay up to date with the site changes, but at the same time provide the raw data for devs who want to save it and do stuff with it.

**Comment by sagiba** [comment]
@eshaham no problem with attaching the raw data to the result, that's good and actually what I wanted originally. Later I figured that I also need to be able to re-use the existing converters so that I can re-process existing raw data, and add unit tests, etc. So we also need to extract the converters, and make them injectable. Merely returning the raw data is not an alternative for this.

**Comment by eshaham** [comment]
@sagiba got it
@esakal any final thoughts?

**Comment by esakal** [comment]
I think there are two different requirements here. Providing a way to shape the transaction result when user provide interceptor will solve this issue.

The second one, talking about separating the converters is something else and we can/should discuss separately. thoughts about this one:
1. I don't see the benefit of letting people to replace converters because it make the api fragile. I do think it can help with unit-tests which is something to wish for usually. But in our case where the converters are tight directly a 3rd party api, the companies websites, what exactly are you going to test? the fact that they pass doesn't mean the logic will not break because it depends on external api which is our of our hands.

2. If will proceed with the adapters architecture we are going to support it anyhow because we will have a dedicated adapter for that conversion. The adapters are more powerful and let you do much more while supporting it out-of-the-box. 

So I think we should address the original issue here and decide how to let people shape the transaction object ([previous comment](https://github.com/eshaham/israeli-bank-scrapers/issues/418#issuecomment-639694929))  and wait with the conversion.

**Comment by sagiba** [comment]
@esakal 
> I don't see the benefit of letting people to replace converters because it make the api fragile.

The benefit is that your target users are asking for it ;-)
and if you won't do it, then some people who are eager to make things work their way will fork away your repo, and you will lose their contributions. This isn't a good place for an open-source project to be in.

I already maintain my own fork that meets my requirements, so things work for me. I've been hashing this issue with you for almost two months now because I don't think it's good for the project health for people to have to maintain their own forks. We will achieve more if we work together.

I don't get your point about "API fragility". This entire project is fragile by definition, as any of the websites can change their interfaces in any time and break everything. I know we are making best efforts to catch-up with such changes and release new versions quickly when things break, but because this is a library, whoever who uses it is still forced to, at the very minimum, pull a new version to receive the fix. It's not that things will just work automatically forever if you stick to the current mechanism, and break over-and-over if you make an extension.

If a user of this library cares enough to replace the converter, which requires substantial work and understanding on top of using the standard API, then it's safe to assume that he'll also be capable of adapting to whatever future changes that will come up. There's no need to protect anyone here.

If you want to add another safety guard, then maybe we can add a version string to the raw data formats. So we can mark the existing Cal format something like cal_v1 for example, and provide it along with the raw data object. Then someone who writes his own converter can check this version and throw an exception if getting an unsupported version.

> I do think it can help with unit-tests which is something to wish for usually. But in our case where the converters are tight directly a 3rd party api, the companies websites, what exactly are you going to test? 

The unit tests need to be part of the library, for the standard converters, not just for custom converters. The conversion logic is often fragile, and the current implementation contains many bugs. For example, some converters have no IDs, some have non-unique IDs, some have bad currency codes, etc. I've fixed many of these issues, and every time I make a fix I try to have a corresponding unit test, that shows how the raw data looks (for a real transaction, that I scraped from the account, after anonymization), and how the converter result should look like.

**Comment by esakal** [comment]
@sagiba 
> The benefit is that your target users are asking for it ;-)
and if you won't do it, then some people who are eager to make things work their way will fork away your repo, and you will lose their contributions. This isn't a good place for an open-source project to be in.

Actually I stopped reading after this paragraph. What you are mentioning here is lose-lose situation. You probably don't want to maintain your own fork the same as I will hate to see you leaving.

We are both handling this discussion for two months now not only you. Since I respect your opinion I continued to discuss about this one with you. 

Obviously you are a strong developer and you have solid opinions about architecture and best practices - as well as I consider myself as an experienced architecture and developer. We don't need to agree about specific architecture and it is fine.

I mentioned several times that we are considering a way to make this library extendible and extremely powerful, you could have ask for details about it and show interest, maybe it will actually do what you want and let you do more powerful things. We have put that on hold till we finalize the Transactipt PR.

I respect the time of anyone who is willing to contribute to open-sources. I also spend many hours every month contributing to this library as well as few other volunteer projects. 

I'm sorry that you are feeling frustrated, feel free to continue promoting this one directly with @eshaham.

**Comment by sagiba** [comment]
Thanks @esakal. I'm sorry if this came as too harsh or disrespectful, that's not wheat I meant. I know you are spending a lot of time and energy in improving this library and I'm grateful for your efforts.

I opened a new issue #458 to sync on the roadmap, can we please continue there?
