### ISSUE TITLE
Puppeteer types are imported from the puppeteer package instead of puppeteer-core 

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#518]
In the `israeli-bank-scrapers-core` package, in the `next` version (`0.9.2-dev.83c4b6641`), there are imports of types from `puppeteer` instead of `puppeteer-core`. This causes compilation errors, see:

![Screen Shot 2020-09-09 at 15 00 33](https://user-images.githubusercontent.com/7272927/92596644-cdd8f300-f2ae-11ea-9864-d720eb8f79bd.png)

**Comment by esakal** [comment]
@brafdlog Hi, thanks for reporting about it. After some investigation I improved the code modification logic and made sure the source code is using puppeteer-core across all sources so it will reflect like that in the defintion files.

Can you pull locally and verify that it solves your problem?

**Comment by brafdlog** [comment]
@esakal I as wrote in the PR it looks fine.

Can this be merged?

**Comment by esakal** [comment]
@brafdlog Hi, we need @eshaham for that....
We perform CR to each other before merging to master each other . Since you checked it on your machine I don't mind merging it but we will need Elad anyhow to deploy a new version to NPM (I don't have credentials).

If I will merge, you will be able to use the next version which is deployed automatically from master, if it can help you I will merge it to master and you will be able to use it in the meanwhile using `npm install israeli-bank-scrapers@next`. 

Let me know if the `next` version helps and if so will merge it.

**Comment by brafdlog** [comment]
I understand. No need to diverge from your regular pr practices. I am currently working with a version of the package that i published from a fork of your repo to solve this. When you are ready and merge i will use the @next version.
Thanks
