### ISSUE TITLE
Failing to scrape Hapoalim from Node server with Generic errorType

### ISSUE THREAD

**Issue by MSDevs** [eshaham/israeli-bank-scrapers#532]
Hi guys

I've tried running the example from readme from a basic nodejs application.
Using `hapoalim` its constantly failing with:
```
{"success":false,"errorType":"GENERIC","errorMessage":"text is not iterable"}
```
Other companyIds work well, tried with `otsarHahayal` for example.

When using `showBrowser=true`, I can see the page is not loading properly (blank white page).
Yet when navigating manually to the same URL, the login page is loaded as expected.

I've also run the same code with `hapoalim` from an `electron` app, and it works well there. 

What am I missing here?

Thanks a lot for your help

**Comment by esakal** [comment]
@MSDevs I"m not sure what is the right way to tackle this one. because you are saying that it works in electron and also that other companies does work in node. so we can eliminate incompatible node version or wrong configurations on your side. 

I think the best way will be to [debug using the ide](https://github.com/eshaham/israeli-bank-scrapers/blob/cf92390be739dbe3cc6e140c9ece9ad967e4f95e/CONTRIBUTING.md#running-tests-using-ide). since you mentioned that you don't see the login page, i suggest you to set a breakpoint [here](https://github.com/eshaham/israeli-bank-scrapers/blob/ab7d0b4ac3b562ab73605d6e835590bad7713588/src/scrapers/base-scraper-with-browser.ts#L195) and continue from that point till you find where the error is thrown from. If your IDE doesn't support debugging, setting console.logs might also help.

Use the contribution [guide](https://github.com/eshaham/israeli-bank-scrapers/blob/ab7d0b4ac3b562ab73605d6e835590bad7713588/src/scrapers/base-scraper-with-browser.ts#L195) for running debug on the source codes so you will be able to debug the sources and not the dist folder.

Let me know what you found.

**Comment by MSDevs** [comment]
@esakal Thanks for the quick reply. 
I debugged the app as you suggested. My bad. In the process of generalizing the solution, I accidentally was using `username` instead of `userCode` for `hapoalim`.

**Comment by podj** [comment]
> 

@esakal I just got this error too.
Perhaps we should add validations to each scraper's input?
