### ISSUE TITLE
problem after upgrading package to ^1.0.0

### ISSUE THREAD

**Issue by liranso** [eshaham/israeli-bank-scrapers#541]
i'm getting the following error (on both mac and linux) - Error: Cannot find module 'puppeteer-core'
after installing "puppeteer-core" i'm getting - 
"scraping failed for the following reason: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary."

only workaround is using "executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" in the options json for "createScraper".

And event after that, max login does not work

Thanks!

**Comment by esakal** [comment]
hi @liranso. chromium 818858 seems to be valid version as you can see in the attached image. can you please elaborate about the way you integrate `israeli-bank-scrapers-core`?
1.  in which environment (ie electron?)
2. how did you download chromium version 818858?

Maybe it is obvious but I will write it here just in case. The only reason to use `israeli-bank-scrapers-core` (which use internally `puppeteer-core`) is if you want to reduce the bundle size of your application, for example when you work with electron you want the bundle to be small thus you use the `-core` library to exclude 100Mb of chromium, and download the relevant chromium later in an applicative way.

If you don't want to worry about it, you should use `israeli-bank-scrapers` which downloads the relevant chromium during the installation.

I hope this help, let me know

![image](https://user-images.githubusercontent.com/4751797/101684532-3df24300-3a6f-11eb-8d63-ca785b4d4d60.png)

**Comment by DoriDembinsky** [comment]
Hi @esakal,
I'm having the exact same issue as @liranso.
And I'm not using israeli-bank-scrapers-core, I'm using israeli-bank-scrapers. 
I get the exact same message that he got, and when doing his workaround, It makes me go around this issue but as @liranso mention, the actual login into max doesn't work after it.

**Comment by DoriDembinsky** [comment]
I tried a fresh install by creating a new directory with a clean package.json and no files. 
I ran `npm i israeli-bank-scrapers@1.0.0 --save`

This is the output
```
> puppeteer@5.5.0 install /Users/dori/Development/test/node_modules/puppeteer
> node install.js

Downloading Chromium r818858 - 132.4 Mb [====================] 100% 0.0s
Chromium (818858) downloaded to /Users/dori/Development/test/node_modules/puppeteer/.local-chromium/mac-818858

> core-js@3.8.1 postinstall /Users/dori/Development/test/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> husky@4.3.5 postinstall /Users/dori/Development/test/node_modules/husky
```

As you can see the chromium version is 818858.

I hope it helps @esakal

**Comment by esakal** [comment]
@DoriDembinsky indeed it is useful. In package-lock.json we lock version to 5.1.0 as you can see in my machine below. But your code shows that you are using latest which is 5.5.0 (`puppeteer@5.5.0 install /Users/dori/Development/test/node_modules/puppeteer`)...

We need to understand why your machine doesn't respect the manifest in package-lock file. any chance you are using yarn instead of npm? 

If you are using `npm` please:
1.  make sure you deleted `node_modules` before running npm install, or better yet run `npm ci` which will make sure you get the right versions. 
2. check in `node_modules/puppeteer/package.json` which version was installed for you.

Let me know.


![image](https://user-images.githubusercontent.com/4751797/101990760-f529cc80-3cb0-11eb-814f-8228aef5eba9.png)

**Comment by DoriDembinsky** [comment]
So the reason is that your package.json has the following:
`"puppeteer": "^5.1.0"`

This actually doesn't ensure that it will install version 5.1.0.
because it has ^5.1.0 it installs the latest minor version which is 5.5.0.
If you want it to be strictly 5.1.0 it needs to be changed to 5.1.0 without ^

**Comment by esakal** [comment]
Actually package-lock.json was created to prevent such a scenario. It doesn't really matter what you have in package.json, if the following conditions are met:
1. npm install honors package-lock.json only if it satisfies the requirements of package.json.
2. If it doesn't satisfy those requirements, packages are updated & package-lock is overwritten.

5.1.0 honors ^5.1.0 so it should be the one that is installed.

Questions:
1. are you using npm or yarn? (should be npm)
2. what version of npm and node do you have?

**Comment by esakal** [comment]
@DoriDembinsky you are right! In my setup I already have puppeteer thus I didn't see it when I re-ran the installation. Before we lock the puppeteer version in package.json let's check first that it works for you. Please do the following:

1. create a new folder
2. run `npm init`
3 *new step* run `npm install puppeteer@5.1.0`
4. run `npm install israeli-bank-scrapers`

The new step will enforce having puppeteer 5.1.0 in your project. Check that it works, If it does, run `npm ci` just to confirm and test again.

If both passes I will work on deploying new a patch for that.

**Comment by DoriDembinsky** [comment]
Yes I tried it already yesterday, it works.
Also the scraping seems to work now as well :)
Thanks!

**Comment by esakal** [comment]
@DoriDembinsky  I'm trying to understand how to continue with this one. Because it is true that new projects will use puppeteer@5.5.0 but it should work as they didn't break the API. see the image below. So I don't think it is needed to lock the version in the package.json to 5.1.0. 

What do you think? 

@eshaham please review previous messages and advice

![CleanShot 2020-12-15 at 13 23 34@2x](https://user-images.githubusercontent.com/4751797/102209193-1836c500-3ed9-11eb-8ba4-940f9b386749.jpg)

**Comment by esakal** [comment]
@eshaham what do you think?
@liranso can you update how it ended on your side?

**Comment by eshaham** [comment]
@esakal the only thing I'm thinking here is that puppeteer 5.5 might break `israeli-bank-scrapers-core`
if there's evidence that version 5.5 may not work in all scenarios, perhaps we should specify 5.1 specifically for now?
wdyt?

**Comment by esakal** [comment]
Let's wait and see if people complain about it because my tests did show that latest puppeteer breaks our library.

**Comment by liranso** [comment]
@esakal sorry for the late response
I used "israeli-bank-scrapers" and not "israeli-bank-scrapers-core"
the only way it works is to use that version in package.json -     "israeli-bank-scrapers": "^1.0.1-next.1",
