### ISSUE TITLE
Bank Leumi - changed the transaction page and it seems to be broken..

### ISSUE THREAD

**Issue by izikf89** [eshaham/israeli-bank-scrapers#564]
Its look like there is a version change (from ASP.net to angular)
The issuse starts with leumi.ts file row 246: "const accounts = await dropdownElements(page, 'select#ddlAccounts_m_ddl');" account exist but script not find them,

**Comment by ifeins** [comment]
I've encountered this issue as well, when I'm scraping Leumi I get the following output:

```
scraping Bank Leumi
Bank Leumi: START_SCRAPING
Bank Leumi: INITIALIZING
Bank Leumi: LOGGING_IN
Bank Leumi: LOGIN_SUCCESS
Bank Leumi: TERMINATING
Bank Leumi: END_SCRAPING
success: true
0 csv files saved under /.../Transactions
```

Even though there are bank transactions in this month

**Comment by esakal** [comment]
@ifeins  @izikf89 as they changed the transaction page it will not work until someone will adjust the Leumi scraper. @ifeins it result with success because they didn't "kill" the previous page but instead redirect silently to the new page and the HTML structure there result with 0 transactions as it looks for the old structure.

**Comment by esakal** [comment]
@ifeins  @izikf89  I created a PR to adjust the scraper to the new site. If you can pull the PR and verify it.

**Comment by ifeins** [comment]
@esakal Tested it and it worked, thanks for the fix 👍

**Comment by esakal** [comment]
@ifeins that is great, Lets wait to verify the pending in the weekend and then I will be able to merge it.
@eshaham if you can check the PR in the meanwhile. 
Thanks
