### ISSUE TITLE
[SECURITY]: request (epic): provide a "zero trust" way to use your library

### ISSUE THREAD

**Issue by zavelevsky** [eshaham/israeli-bank-scrapers#588]
Currently, users of this tool are required to trust it with their credentials.
This is true both for users who run this directly or 3rd party apps that wrap and use this tool.
In fact, we can identify three points of potential exploitation by library maintainers or by attacker who get access to its npm registry:
 - leaking the credentials (possible in several ways)
 - performing unauthorized operations on the user's bank account
 - leaking banking and credit information

Therefore, ideally, we are looking at a set of usage models that address these concerns progressively. To clarify what I mean: A user that fully trust it will use same as today. A user who is worried about sharing their credentials will use in a bit more complicated way, where it's up to them to apply the logic to pass login challenges. A user who is also worried about providing access to their bank account will use your scraping and parsing code - as a library.

So what I believe should happen is:
 - extract and publish the parsing code as a standalone library that does not perform any network access or file system access. This will allow users to safely use this code in order to parse scraped data.
 -  do the same for the scraping code (or client scripts) - to allow users who want to manage the puppeteer session themselves to run it 
 - Add API that allows the user to provide a login challenge callback that is called when puppeteer gets to the login screen - so the user can perform this bit of automated access themselves.

related: https://github.com/brafdlog/hiuvi/issues/264

**Comment by esakal** [comment]
Kudos @brafdlog  for creating this open-source. I always appreciate and enjoy seeing people contributing on their free time to the community. I also developed a similar application during the last year that uses israeli-bank-scraper to import transactions into YNAB, using Electron with React. In the end, I decided to archive it because I understood that there isn't a proper way to provide an application that will be as protected as I would want to.

@zavelevsky nice to meet you. 

> * leaking the credentials (possible in several ways)
> * performing unauthorized operations on the user's bank account
> * leaking banking and credit information

@zavelevsky , those are all valid and concrete concerns that I also had, which eventually led me to archive my project as written above. With the suggestions you mentioned, it might feel more protected, but it isn't. Whenever the user exposes sensitive credentials, they need to understand that they are exposed to considerable risk, at least until the regulations of Open Banking will land in Israel, hopefully by the end of 2021. 

Based on your comment, I believe you are already aware of many security hacks out there, including stealing npm deployment keys, running post-install scripts, hiding malicious code by writing it in base 64, sharing a snapshot of an open-source code base that is not the one being used to pack the binaries, and more. 

> extract and publish the parsing code as a standalone library that does not perform any network access or file system access. This will allow users to safely use this code in order to parse scraped data.

This suggestion, although it will achieve the desired isolation, in my opinion, it is not applicable in real scenarios. The scraping and the parsing logic are strongly tight; the hard part is doing the scraping, and there is no actual value using the parsing logic only. If you managed to scrape the data, it would be easier for you also to parse it. 

> do the same for the scraping code (or client scripts) - to allow users who want to manage the puppeteer session themselves to run it. 
>
> Add API that allows the user to provide a login challenge callback that is called when Puppeteer gets to the login screen - so the user can perform this bit of automated access themselves.

You can, with latest israeli-bank-scrapers version, provide a custom Puppeteer instance, so to complete your suggestion, we can allow passing an option to suspend the login logic. If you find it useful, we can consider it but also here I don't believe it will be that beneficial because:
- In general, users don't like to type things manually, and they usually don't remember passwords, so I don't believe they will be engaged to that approach anyhow, and the ROI is not that high, to begin with. If they still decide to do so, they will have a false sense of protection, as explained below.
- It affects only scrapers that are using Puppeteer. There might be scrapers that are using HTTP—requests like visa cal. 
- Handling the login of each scraper on the application level is not that straightforward. Owning the process means that you'll write the login flow in the application that consumes israeli-bank-scrapers and move the problem mentioned from the library to the application.
- You suggested that the user's responsibility is to log in by mixing an automated process with a manual one. So the library/application will open a browser using Puppeteer and then pause the process on the login page and let the user manually log in.  So now the user thinks his/her credentials are safe, but then who guarantees that the application, israeli-bank-scrapers, or any third party on the project, doesn't register to the keystroke events, record the user activities, or wait for the user to login and then perform an operation on his behalf (CSRF or others).

Security is all about creating roadblocks, but I'm not sure your suggestions make it harder for hackers.

**Comment by brafdlog** [comment]
Thanks @esakal . @baruchiro are working on this together.
I started the same as you, from a script for my own use but then I saw how beneficial it was so I wanted to share it.
As you say, giving your bank credentials to a program like ours is risky. There are many attack vectors, and giving them appropriate attention would require a very significant amount of work. We are doing this as a side project with very limited time to invest in security so, it is risky :)
That said, this can provide a lot of value to people, so we want to give people the ability to choose whether the risk/reward is worth it for them or not.

**Comment by zavelevsky** [comment]
As a side note, I'd recommend everyone that wants to use such tools, to get their hands on read-only credentials. Sadly, in Israel a set of credentials goes with a real person - so this option exists for shared accounts only - where one of the owners is ok with having only this limited access.

**Comment by erikash** [comment]
@esakal I agree with everything you said - but *personally* (not sure if I'm the mainstream here but could be) I would love to enter my credentials manually :)

**Comment by esakal** [comment]
@erikash Hi,  can you elaborate on the gains you believe you'll have when entering the credentials manually?

Keep in mind that this is usually a node (server-side library) where you don't have user interactivity. 

And for Electron, it can be done but keep in mind that:
- you are still potentially exposing your credentials, the application that will initiate the puppeteer instance can add listeners that will audit the keystrokes
- the UX will not be attractive/practical as the application will need to show you the puppeteer instance in a separate window, provide you a way to "signal" them that you are logged in, and then keep it open while the library continue the scraping
- as you are connected, you are still exposed to csrf vulnerabilities (someone who leverage the fact that you are connected and send requests on your behalf)
- I don't remember which institute is not using puppeteer, and you cannot just log in

I'm not trying to convince you; I think it will cause more damage as users might tempt to think they are secure. 

What do you think?

**Comment by esakal** [comment]
I'm going to close this issue. If someone want feel free to comment
