### ISSUE TITLE
Issues with specific visaCAL input

### ISSUE THREAD

**Issue by tpseven-777** [eshaham/israeli-bank-scrapers#591]
Hi,
I'm getting the following error when trying to fetch transactions from Visa cal.
This error is stable for a few days now, and relevant to a specific month only.
Could very well be something wrong with Visa cal site itself, but is there any way to verify that?

`invalid json response body at https://cal4u.cal-online.co.il/Cal4U/CardsByAccounts reason: Unexpected end of JSON input`

**Comment by netanelbrauner** [comment]
Got same error too.

**Comment by tpseven-777** [comment]
Got this now for a second card in that month. Anything to do?

**Comment by kostyay** [comment]
Same here

**Comment by esakal** [comment]
Hello,
As I manage to scrape visa cal as always, there are two options:
1. your transactions include data that I don't get and is causing this issue.
2. you are not using the latest israeli-bank-scrapers version. 

It is easy to rollout the second one, please update to latest `v1.3.1`, or reply if you already tried it.

Thanks
Eran

**Comment by tpseven-777** [comment]
I've upgraded to the last version, and I still experience this.
Also I've notice this issue is inconsistent. It can appear and disappear and I can't tell the reason.

**Comment by tpseven-777** [comment]
Anything we could do here? @esakal

**Comment by ifeins** [comment]
@esakal I'm experiencing this issue as well

**Comment by esakal** [comment]
I'll check and update

**Comment by esakal** [comment]
I'm not sure if we can do anything, because the login api returns a token that we cannot verify but seems valid. 
see this example, a valid auth that still fail the scraping 
![CleanShot 2021-08-05 at 16 26 50@2x](https://user-images.githubusercontent.com/4751797/128358799-70fd68c6-f8bb-468e-9868-f41946315bd2.jpg)

and another run just right after that works
![CleanShot 2021-08-05 at 16 27 32@2x](https://user-images.githubusercontent.com/4751797/128358903-847d69f0-2b46-4db7-89a6-479ff3e60e5d.jpg)

If I provide  wrong credentials the auth returns error as expected. 
![CleanShot 2021-08-05 at 16 38 53@2x](https://user-images.githubusercontent.com/4751797/128359569-a9f5c31d-7bff-4174-b490-8e19734fa074.jpg)

Based on the examples above I suspect this is something in their server.

We can return a more relevant error from the fetch util, as you can see in the examples above, so we will know if the failures are due to http request not resulting with 200.

wdyt?

**Comment by esakal** [comment]
@ifeins @tpseven-777 I have an idea that might help. in the attached PR I replaced the api used to login. We don't look for 100% success but I hope this api doesn't suffer from the other login api issues. 

Please let me know how it worked for you
