### ISSUE TITLE
fix union scraper

### ISSUE THREAD

**Issue by orentet** [eshaham/israeli-bank-scrapers#598]
Hi
Great job on this project.
the union scraper is not working for quite a while now.
I provided a fix in #566 but was not accepted.

personally i don't have time for more than the fix, and personally i'm using my own branch which fixes this issue for me, but for the sake of everyone else and other projects that rely on this project. please fix it.

if you need me to test a fix, i'd be happy to test it.

**Comment by esakal** [comment]
@orentet Hello :)
Actually we can almost add it, the changes are not complicated but I'm not sure we can ignore them. 

```
    waitUntilElementFound(page, '#restore', true),
```
When you changed the selector of singing you removed the promise.race and now it doesn't support restore. You can just revert to the original version with the promise.race and change the first selector like you did. It will work.

```
    return (option as HTMLElement).innerText.replace(/[^ -~]+/g, '');
```
this one I dont understand how it works, because basically you replace all characters that are not the problematic symbol, -~ so `123-123` will become `-`

Am I missing something?
