### ISSUE TITLE
Visa cal issues with an account that has multiple cards

### ISSUE THREAD

**Issue by tpseven-777** [eshaham/israeli-bank-scrapers#633]
Hi,
I've just upgraded to the latest version, and everything works except that account.
It's a visa-cal account with 4 (!) different cards. some of them are not active, but some are.
I was getting the following error:
`Error: failed to find element matching selector "[id$=FormAreaNoBorder_FormArea_ctlMainToolBar_lblCaption]"`
I also have another visa-cal account with just a single card, scraping works well there.
Please let me know if you need further info

**Comment by esakal** [comment]
Hi @tpseven-777 
I believe it is because of the not active cards because for others with multiple accounts it works.
Two options:
1. create a PR and filter out the inactive accounts.
2. share snapshots and also selector that might help identify those inactive accounts

The best option will be a PR from you as you will be able to test it at the same time. If for any reason it is not possible lets try to resolve it with option 2.

I believe the code that should be modified is https://github.com/eshaham/israeli-bank-scrapers/blob/3fcfb7a5cd619a33a7022cc2708a45c084c7f529/src/scrapers/visa-cal.ts#L263 but this is only a guess

Eran

**Comment by esakal** [comment]
@tpseven-777 Hi. I believe the problem is not due to multiple cards. Can you check the PR #635 and let me know if it works for you?
