### ISSUE TITLE
Visa cal - error "Navigation timeout of 30000 ms exceeded"

### ISSUE THREAD

**Issue by agammyshhay** [eshaham/israeli-bank-scrapers#696]
Hi,

thanks for this important project.

in Visa cal i get error :"Navigation timeout of 30000 ms exceeded"
im working with Caspion

thank

**Comment by esakal** [comment]
Does it continue to happen to you ?

**Comment by agammyshhay** [comment]
No, its stopped
thanks

‫בתאריך יום א׳, 26 ביוני 2022 ב-16:44 מאת ‪Eran Sakal‬‏ <‪
***@***.***‬‏>:‬

**Comment by LiranBri** [comment]
reproduced to me

**Comment by ifeins** [comment]
I'm getting the following error:

```
scraping Visa Cal
Visa Cal: START_SCRAPING
Visa Cal: INITIALIZING
Visa Cal: TERMINATING
Visa Cal: END_SCRAPING
success: false
error type: TIMEOUT
error: wait for iframe with login form
Error: wait for iframe with login form
    at _default (.../israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
```

**Comment by kazazor** [comment]
Same here, exactly like mentioned by @ifeins

**Comment by kazazor** [comment]
Seems to me that the issue is just a change in the login iframe URL.
It used to be something with `connect.cal-online` and now it's `calconnect`.

So in this line: https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/visa-cal.ts#L45

Just change from:
```js
f.url().includes('connect.cal-online')
```

to:
```js
f.url().includes('calconnect')
```

That solved that for me, can someone else verify it? If it works for everyone else I can open a PR for that :)

**Comment by LiranBri** [comment]
still reproduced to me :|
