### ISSUE TITLE
Discussion: Add future debit charges for the bank accounts

### ISSUE THREAD

**Issue by kazazor** [eshaham/israeli-bank-scrapers#707]
# The goal

Be able to see my current balances (already possible) and the future charges I should expect from my credit cards according to their next charging date.
That will help not just reading the history of the charges, but also getting the current status in an easy-to-use way.

# What exists on the bank website?

In the credit card section of each bank website, you have all of your credit cards, their charge date, and the accumulated charge amount.

By default, only the bank-issued credit cards appear, but anyone can request to also see the accumulated charges from other issuers (cal, max, isracard).
Due to that, in order to see the charges on the next charge date - there is no real need to fetch that data form cal/max/isracard because the banks are taking care of that.

# What exists today in this repo?

In his PR, https://github.com/eshaham/israeli-bank-scrapers/pull/656, @LiranBri added it for Cal - `futureDebits` :
```js
export interface ScaperScrapingResult {
  success: boolean;
  accounts?: TransactionsAccount[];
  futureDebits?: FutureDebit[];
  errorType?: ScraperErrorTypes;
  errorMessage?: string; // only on success=false
}

export interface FutureDebit {
  amount: number;
  amountCurrency: string;
  chargeDate?: string;
  bankAccountNumber?: string;
}
```

By the way, this is not documented in the readme file at the moment.

This was a very cool addition that is highly needed IMO.

# What do I think we should do?

After I talked offline with @LiranBri , and like I said before, IMO this information should really just be in the bank accounts and not the other vendors.
More than that, IMO this data should show the charges for each credit card separately so it will be more generic. At the moment it's grouped by the bank account number - so again it's all coming back to the bank account.

So here is what I'm suggesting:
1. Remove the `futureDebits` object added by @LiranBri + remove this code from the Cal scraper (it won't be a breaking change as it's undocumented anyway..)
2. Replace it under the standard `account: TransactionsAccount` object:
```
export interface TransactionsAccount {
    accountNumber: string;
    balance?: number;
    txns: Transaction[];
    futureCharges?: FutureCharge[];
}

export interface FutureCharge {
  amount: number;
  amountCurrency: string;
  chargeDate: string;
  cardLastFourDigits: string;
  issuesByTheBank: boolean;
  issuer: string; ("מקס, ישראכארט, כאל")
}
```

IMO that will introduce a more generic way to get ALL the future credit card chargers which will be more aligned with the way the current code works and separation by card.

# What can I do?

I can go ahead and do that for the Hapoalim bank, and so create the infrastructure for this to be implemented on other bank scrapers.
But before I do that, I would like to get @LiranBri and @erikash opinions so I won't develop it for nothing :)
WDYT?

**Comment by LiranBri** [comment]
I think it makes much sense. I like it.

BTW, maybe we should make the interface fit also future scheduled charges defined in the bank website itself (הוראת קבע). Even if not implemented currently. 

 I think "Debit" is the official terminology, and not "Charge". Correct me if I'm wrong

**Comment by kazazor** [comment]
I like the idea of preparing the interface also for future scheduled charges.
I'll take a look at it and comment back how it can look.

Regarding the name, debit got me thinking about debit cards, but I don't mind - can be called futureDebits instead :)

**Comment by erikash** [comment]
Hi guys,
Thanks for mentioning me @kazazor 
TBH I have no need for this feature as I use YNAB and there is no way in the interface to reflect this information but "scheduled transactions" - and as we're talking about future transfers between a bank account and a credit card which amount will be increasing/decreasing per charge it will get messy as YNAB assumes transactions (including transfers between a bank account and a credit card) are immutable.

Regardless, if not using YNAB I guess this can come pretty handy but consider the following reasons I think this is a bad idea:
1. Two sources of truth - you can calculate balance A using the credit card transactions and balance B can be shown in a Bank Account. Which one is correct? 
2. It introduces unnecessary coupling between bank accounts and credit card providers - first, you assume all banks support reflecting all card balances and second if you add a credit card provider you would need to update all bank scrapers otherwise people can mistakenly assume all cards are already accounted for...
3. Even if you add all credit cards as "futureDebits" it's not an exhaustive list  - what about Paypal? Paybox? or any other wallet? I wouldn't create this expectation in by exposing it on an account object...

From a design perspective I like @LiranBri 's initial implementation.. 
it just makes much more sense IMO to add "futureDebits" as a feature per card issuer - it creates less coupling and is more flexible to extend with other features which not all issuers/banks might provide...

**Comment by LiranBri** [comment]
@erikash I understand your concerns, and I do agree that it would be ideal to have this implemented from the credit card isuers crawler (like the PR I contributed).

However, to be honest I'm not sure its practical to expect this to be implemented on every credit card scrapper. going with @kazazor approach is much more reasonable as its a very fast and robust win that would give out-of-the-box support for that information from ALL credit cards issuers related to the bank account, without being exposed to specific one introducing any breakable change, etc.

so just because its much more practical, I suggest to let @kazazor implement his suggested PR

**Comment by erikash** [comment]
Thanks for the clarification @LiranBri 🙏
Sure, fast and practical wins every time!
Good luck and great initiative @kazazor 💪

**Comment by kazazor** [comment]
* This is mandatory by law in Israel for all banks as part of the Open banking laws, so yes - all banks support it - so you can have it in Leumi as well :) (And I actually see this for Leumi: https://www.leumi.co.il/Articles/38758/)
* Here is also an article about it from January 2020: https://www.ynet.co.il/articles/0,7340,L-5668325,00.html
* You see all your external cards with no exception
* Foreign transactions are included in the accumulation of the future debit amount
* I was able to see the vendors I work with: Visa cal, Isracard & max.
* The process to do that, in most cases I know, is on the vendor side. All banks support it by default, so you just need to ask your vendor to send this data to the bank so it will be displayed on your bank's website. Here is an example of visa-cal: https://www.cal-online.co.il/about/legal-reports/open-banking/ just click the button there and fill out the form :)
* While I get the single source of truth debate, it's not 100% accurate. The data is being sent from the vendors to the banks. So the bank doesn't really process/creates a copy of the data. The single source of truth is still the vendor. On the bank's website, you only see the accumulated future debit charges, but if you want to see the actual details it actually sends you back to the vendor's website to see it (as it doesn't hold this data on the bank's records). So IMHO there is still only one single source of truth, it's just that Israeli laws have given us a shortcut here :)

Here is an example:
![Screen Shot 2022-07-10 at 23 32 59](https://user-images.githubusercontent.com/1577655/178161269-508baa31-a73f-4a99-a089-25fe14b5d6c5.png)

To me all of that sounds safe and quick to implement, WDYT? :)

**Comment by kazazor** [comment]
By the way, the only "problem" I have with the current implementation done by @LiranBri , is the fact it's "outside" of the standard account object of the result.
Meaning I cannot know which credit card holds the future debit, it's by bank account and not by credit card.

We can also think about changing that instead of relying on the bank's integration (even if it's mandated by law).
At least for Cal I know that's possible, but I haven't checked max & isracard and how easy is it to do it.
I can say that on Cal it's doable but will take more time than the bank. On the bank's website, you just need to go to this page and you have all the data.
On Cal, for example, you need to click on each credit card you have to fetch the data.

So I'm cool with all options to be honest.
Let me know what you think :)

**Comment by erikash** [comment]
BTW:It's been a while since I've looked at the code...I've looked again at the Cal scraper and the transaction API has `processedDate` (which should be called settlementDate probably), that is exactly what you're looking for @kazazor ...
To get he `futureDebits` all you need is to aggregate the transactions by these field and summarize the groups.

Does this make sense?
@esakal am I missing anything?

**Comment by kazazor** [comment]
Thanks @erikash ! I think there are a few challenges here:

1. The naming is confusing of course :) I'll go over it soon and verify this is actually what this field represents.
2. The charges on the charging date might be from more than 3 months before the date. There are cards that give you this is benefit. So for example, to know the charges on my card for Jul 15th, I'll have to go over transactions from at least April 1st. And I guess there might be benefits that give you even more time.. So we might think we got it right, but maybe we're missing charges..

Instead, there is a dedicated section for it on both the bank side but also the vendors side. To me, it doesn't really matter which side we choose, but I think the approach of going over all the transactions and grouping them has a risk to miss data.

**Comment by kazazor** [comment]
To me single source of truth is the fact the vendor holds the data. If it's the transactions from the vendor or a number the vendor aggregated for me - to me it's the same as it drives from the single source of truth from the vendor.
So I personally treat them the same and don't see a problem there.

I guess the last 3 months can be good enough, let me give it a try and see. Still need to verify the`processedDate` is actually what we want :)

**Comment by esakal** [comment]
Hi :)
@erikash `processedDate` should do the trick and I agree the name is not that ideal.

@kazazor, I wasn't aware that we reached to that milestone in the open banking. Since it is part of the regulation thus should apply to all vendors I believe we can continue with your suggestion. 

As users of this library must issue manually a request to include their cards, I believe we should provide  instructions in the readme.md how to do that. 

Also as we will probably not support all bank vendors from day one, we should consider adding in the readme.md also a list of supported bank vendors

we didn't document #656 mostly because it was added only in CAL. if @LiranBri  is ok with that I agree we should remove it and advice users to use the new support to be added.

@LiranBri  @erikash  @kazazor - if it is fine by you that @kazazor feel free to provide a PR :)

And thanks for the contribution it has been a while since we had such an active discussion on a new feature.

**Comment by LiranBri** [comment]
Go ahead 💪

**Comment by erikash** [comment]
Go ahead!

**Comment by eshaham** [comment]
Love the discussion here and where this is going 💪

**Comment by LiranBri** [comment]
I think it makes much sense. I like it.

BTW, maybe we should make the interface fit also future scheduled charges
defined in the bank website itself (הוראת קבע). Even if not implemented
currently.

 I think "Debit" is the official terminology, and not "Charge". Correct me
if I'm wrong.
