### ISSUE TITLE
Hapoalim scraper gets only the first 150 transactions

### ISSUE THREAD

**Issue by skoant** [eshaham/israeli-bank-scrapers#732]

**Comment by esakal** [comment]
Hi @skoant  checking the code base I see it has a magic number 150 which explain why you get only up to 150.

https://github.com/eshaham/israeli-bank-scrapers/blob/81aed787a263a658180a819aa7b2354a1b6203e4/src/scrapers/hapoalim.ts#L141

as it is there since long time ago, and as I don't have hapoalim account, I don't know it is like that because of a concrete reason. Feel free to adjust the number locally and test it ([follow this guide](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#testing-the-scrapers)).

If it works with larger number just create a PR and I'll merge it.

**Comment by skoant** [comment]
Hi @esakal,
Thanks for looking into it.
Please see my [PR](https://github.com/eshaham/israeli-bank-scrapers/pull/738) fixing this issue
BR

**Comment by esakal** [comment]
The mentioned PR was merged a few weeks ago.
