### ISSUE TITLE
[Leumi] GENERIC: waiting for selector `a[title="דלג לחשבון"]` failed: timeout 60000ms exceeded

### ISSUE THREAD

**Issue by podj** [eshaham/israeli-bank-scrapers#746]
Hi, I'm suffering from the following exception:
```
GENERIC: waiting for selector `a[title="דלג לחשבון"]` failed: timeout 60000ms exceeded
```

Is there a way to increase this specific timeout?
Thanks in advance

**Comment by esakal** [comment]
Hello,
Usually it indicate that there is an issue, i'm not sure extending the timeout will help here. 

I recommend you to check what happens when running with `showBrowser: true`. 
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/base-scraper.ts#L61

It might help understanding where you are stuck.

btw, in https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/base-scraper.ts#L98 we have timeout but from the error your provided it looks like Leumi is currently using an hard coded value of 60 seconds

**Comment by esakal** [comment]
@podj feel free to re-optn this issue if it still happens and you tried my suggestions in the previous comment
