### ISSUE TITLE
Pension / Bituach Ishtalmut / Insurance

### ISSUE THREAD

**Issue by amir-daniel** [eshaham/israeli-bank-scrapers#770]
I would like to write a new scraper for some pension / insurance companies. Is this something desirable for us?

**Comment by erikash** [comment]
TBH - I think it's out of  the scope of this library as it's outside the banking segment (scraping securities data such as stocks and bonds would be welcome)

If you're interested, I've founded Mukdam to which will expose this data as an API at some point :)
For now it's just a monthly report and some other insights delivered to you...

https://www.mukdam.co.il

**Comment by baruchiro** [comment]
I see @eshaham started this some time, you may continue :-)
https://github.com/eshaham/israeli-insurance-scrapers

**Comment by eshaham** [comment]
I just deleted it - it had nothing in it, just a skeleton project 😞

**Comment by Wazzaps** [comment]
I get my data directly from the Masleka (https://www.swiftness.co.il), I intercept the ZIP they send every month to my gmail with the gmail api, then parse the XLS inside (much easier than the XML), and store inside sqlite.
Would you like the code for that?

**Comment by erikash** [comment]
Nice!
I would love to see it as well :)

**Comment by Wazzaps** [comment]
Here's my project: https://github.com/Wazzaps/stonks
It's structured as a RESTful api (rather than a library) since that's how I use it, but you can extract that part out.
The interesting part is translating all the keys (which are in hebrew/hebrish) to english, so they can be stored in a DB.
I consume the DB directly with Grafana, my dashboard JSON is attached.

Since I don't have access to the proper APIs (thanks """Open""" banking), I scrape the monthly zip from swiftness that's delivered to my email.

**Comment by esakal** [comment]
Hi @Wazzaps, I like your nickname! Thank you for your suggestion. I agree with @erikash that your idea seems to be outside the scope of this library. However, in general, the library is not too opinionated and allows you to scrape relevant financial information.

I do have a technical concern, though. As the library is not modularized as we hoped, implementing your suggestion may introduce new behaviors, such as using a path to a zip file instead of credentials or skipping the login phase. While this is not critical, it does align with Erik's opinion about the relevance of your suggestion to this library. Additionally, the library will mainly be used as a converter from xls to csv.

I'm open to your suggestion, but I agree that it may not be highly relevant to this library. Does anyone else have an opinion on this? @eshaham @baruchiro?

**Comment by Wazzaps** [comment]
The main problem with signing in to swiftness directly (though it is possible), is they remove the data after some time due to privacy laws.

I guess this is not too different from how most banks work, so it's feasible.

In any case, I think the XLS -> Dict translation somewhat fits the theme of the library, acting as a common language for all providers.

There are probably in-memory zip and XLS libraries for node.js, so working with paths might not even be necessary.

**Comment by tomerh2001** [comment]
Does anyone know an existing scraper [Clal](https://www.clalbit.co.il/) Pension / Keren Ishtalmut scraper?
