### ISSUE TITLE
Adding Mercantile Discount

### ISSUE THREAD

**Issue by Ben2pop** [eshaham/israeli-bank-scrapers#792]
Hi Friends,
would it be able to add Mercantile Discount ? 
I have login if you need help with that 

thx you

**Comment by esakal** [comment]
Thank you for your interest in our node library open source project. 
We appreciate your suggestions. However, we cannot extend the library to include new scrapers for accounts that we don't personally use. This is because our library is dealing with sensitive personal information that belongs to the users. Only a person who owns the account on a website can introduce a new scraper. If you have knowledge in javascript and would like to give it a try feel free to open a PR

**Comment by EzzatQ** [comment]
Mercantile Scraper is now available. See: https://github.com/eshaham/israeli-bank-scrapers/pull/838
