### ISSUE TITLE
Add a charged currency property to transactions

### ISSUE THREAD

**Issue by eshaham** [eshaham/israeli-bank-scrapers#80]
In some cases when users have a foreign currency account in their banks, transactions in that foreign currency get charged directly against the foreign currency bank account, and conversion to `ILS` is not needed.

Currently this module always assumes `chargedAmount` is returned in `ILS`.
We should introduce a new `chargedCurrency` property to transactions that will hold the actual currency used.

**Comment by asfktz** [comment]
I would like to handle that for Isracard and Bank Hapoalim.

One challenge I have it that I'm not sure I've seen a case where a transaction in foreign currency is converted to ILS.

In my Isracard account, I see that some of my transactions are converted to ILS, but the "Original Currency" column is also ILS:

(Isracard)
![image](https://user-images.githubusercontent.com/199747/36499539-3dcf9ae4-174a-11e8-9155-9fffcaa335cd.png)

Note: My credit card is set to transfer money from my `מט"ח` account for foreign currency

Do you have an example of such case?

**Comment by esakal** [comment]
Hi @asfktz, following eshaham/israeli-ynab-updater#22 you mentioned that the transaction contain the following information:
```
{
  "currencyId": "USD",
  "currentPaymentCurrency": "USD",
}
```

can't we use those fields to figure original and charged currency?

Regarding the banks I think we can scrape also the foreign accounts, I can add the Leumi account if needed

**Comment by esakal** [comment]
@asfktz I would like to promote the support for charged currency. Please take a look at #155, I added new field to `leumi-card` named `chargedCurrency` in [charged-currency branch](https://github.com/eshaham/israeli-bank-scrapers/tree/charged-currency). If you can add their support for `Isracard` it would be great.

**Comment by asfktz** [comment]
Better late than never.
I'm working on the `chargedCurrency` field for `Isracard`.


First here are examples of the two transaction types

## Transaction Examples

### 1. A transaction that is charged in foreign currency:
(It charges my foreign currency account directly)

![image](https://user-images.githubusercontent.com/199747/59962957-275fd100-94f5-11e9-8fa5-1796ca33784a.png)

```
{
    "specificDate": null,
    "cardIndex": "0",
    "dealsInbound": null,
    "supplierId": null,
    "supplierName": null,
    "dealSumType": null,
    "paymentSumSign": null,
    "purchaseDate": null,
    "fullPurchaseDate": null,
    "moreInfo": null,
    "horaatKeva": null,
    "voucherNumber": "0069338",
    "voucherNumberRatz": null,
    "solek": null,
    "purchaseDateOutbound": "13/05",
    "fullPurchaseDateOutbound": "13/05/2019",
    "currencyId": "USD",
    "currentPaymentCurrency": "USD",
    "city": "1650485163",
    "supplierNameOutbound": "NOTION SO",
    "fullSupplierNameOutbound": "NOTION SO",
    "paymentDate": "15/05",
    "fullPaymentDate": "15/05/2019",
    "isShowDealsOutbound": "_",
    "adendum": null,
    "voucherNumberRatzOutbound": "804475868",
    "isShowLinkForSupplierDetails": null,
    "dealSum": null,
    "paymentSum": null,
    "fullSupplierNameHeb": null,
    "dealSumOutbound": "5.00",
    "paymentSumOutbound": "5.00",
    "isHoraatKeva": "false",
    "stage": null,
    "returnCode": null,
    "message": null,
    "returnMessage": null,
    "displayProperties": null,
    "tablePageNum": "0",
    "isError": "false",
    "isCaptcha": "false",
    "isButton": "false",
    "siteName": null,
    "clientIpAddress": null
  }
```

### 2. A transaction that is convert to ILS:

![image](https://user-images.githubusercontent.com/199747/59963664-f1274f00-94fe-11e9-892e-1a99eb35a4f4.png)

```
{
    "specificDate": null,
    "cardIndex": "0",
    "dealsInbound": null,
    "supplierId": null,
    "supplierName": null,
    "dealSumType": null,
    "paymentSumSign": null,
    "purchaseDate": null,
    "fullPurchaseDate": null,
    "moreInfo": null,
    "horaatKeva": null,
    "voucherNumber": "0012655",
    "voucherNumberRatz": null,
    "solek": null,
    "purchaseDateOutbound": "14/06",
    "fullPurchaseDateOutbound": "14/06/2019",
    "currencyId": "NIS",
    "currentPaymentCurrency": "NIS",
    "city": "G.CO/HELPP",
    "supplierNameOutbound": "GOOGLE  BLINKIS",
    "fullSupplierNameOutbound": "GOOGLE  BLINKIST",
    "paymentDate": "16/06",
    "fullPaymentDate": "16/06/2019",
    "isShowDealsOutbound": "_",
    "adendum": null,
    "voucherNumberRatzOutbound": "917339015",
    "isShowLinkForSupplierDetails": null,
    "dealSum": null,
    "paymentSum": null,
    "fullSupplierNameHeb": null,
    "dealSumOutbound": "79.90",
    "paymentSumOutbound": "79.90",
    "isHoraatKeva": "false",
    "stage": null,
    "returnCode": null,
    "message": null,
    "returnMessage": null,
    "displayProperties": null,
    "tablePageNum": "0",
    "isError": "false",
    "isCaptcha": "false",
    "isButton": "false",
    "siteName": null,
    "clientIpAddress": null
  }
```

## The Problem
Take a look at the converted transaction (example 2),
In the GUI, you can see that the original amount is `$22` and it is converted to `72.90 ILS`.

Now, getting the `chargedCurrency` is easy, we can use `currencyId` or `"currentPaymentCurrency"`.

But, we also use `currencyId` for the `originalCurrency` already:

 https://github.com/eshaham/israeli-bank-scrapers/blob/560e0cdceb7a1751fa80231319784affd59cc2fb/src/scrapers/base-isracard-amex.js#L110-L111

So, we need to find a way to get the real `originalCurrency` (USD) & `originalAmount`.

The problem is that while we can see it in the GUI, the API response does not return anything that can be used as `originalCurrency` (USD) & `originalAmount` (maybe it rendered server side?)

Any ideas? @eshaham @esakal

**Comment by eshaham** [comment]
@asfktz It's weird that they specify ILS for the original amount, although the transaction was originally USD.
I would probably stick with the currency of what they claim to be the original amount, because, as can be seen in your first example, it can be in other currencies.

**Comment by asfktz** [comment]
OK, so I added `chargedCurrency`, and for Isracard, its always the same as originalCurrency

https://github.com/eshaham/israeli-bank-scrapers/blob/9484be69d0009297a5b5215357eaca304a6b7fe1/src/scrapers/base-isracard-amex.js#L110-L113

I feels a bit awkward knowing that the originalCurrency & originalAmount is wrong.
We know that know, but I don't think it will be clear for anyone else.

**Comment by sagiba** [comment]
Has there been any consensus regarding this issue?

I just ran into it, with a card that had GBP transactions that were charged in USD. For example:
```json
    "currencyId": "USD",
    "currentPaymentCurrency": "GBP",
    "dealSumOutbound": "5.60",
    "fullSupplierNameOutbound": "TFL TRAVEL CH",
    "paymentSumOutbound": "7.59",
}
```

The result of this with the current isracard scraper is:
originalAmount = -5.6, chargedAmount = -7.59, originalCurrency = USD

This is wrong, because the original currency is GBP and not USD.

**Comment by sagiba** [comment]
@esakal can you please re-open this issue?

**Comment by esakal** [comment]
@sagiba I re-opened this one but reading the thread I'm a bit confuse about what can/should be done here.

**Comment by sagiba** [comment]
@esakal, we need to change originalCurrency to map to currentPaymentCurrency instead of currencyId, and add another field, chargeCurrency, that maps to currencyId.

I can take care of this after we agree on #418, because I first want to add some test coverage on the conversion logic here.
